<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/guutz/Desktop/shenanigans/yava/my-project/static/models/poop.glb --root /models/ --shadows --printwidth 120 --precision 2 --suspense
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('/models/poop.glb'))

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-27*.003, -16*.003, 30*.003]} scale={0.003}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_3.geometry}
        material={gltf.materials.Blanco_Ojos}
        position={[19.93, 7.63, -29.25]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_4.geometry}
        material={gltf.materials.Cafe}
        position={[20.5, 16.38, -17.31]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_5.geometry}
        material={gltf.materials.Cafe}
        position={[19.83, 15.68, -16.73]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_6.geometry}
        material={gltf.materials.Custom}
        position={[20.33, 16.43, -34.35]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_7.geometry}
        material={gltf.materials.Default}
        position={[26.68, 16.43, -30.01]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_8.geometry}
        material={gltf.materials.Default}
        position={[14, 16.43, -30.01]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
