<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/guutz/Desktop/shenanigans/yava/my-project/static/models/ssj.glb --root /models/ --shadows --printwidth 120 --precision 2 --suspense
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('/models/ssj.glb'))

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.D_Low.geometry}
      material={gltf.materials['Material.002']}
      position={[0.01, -0.06, -0.12]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.D_Low001.geometry}
      material={gltf.materials['Material.002']}
      position={[0.59, -0.06, -0.12]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.D_Low003.geometry}
      material={gltf.materials['Material.002']}
      position={[-0.61, -0.06, -0.12]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder.geometry}
      material={gltf.materials.Light}
      position={[0, 1.7, -0.08]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder001.geometry}
      material={gltf.materials.Light}
      position={[0.63, 1.7, -0.08]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder002.geometry}
      material={gltf.materials.Light}
      position={[-0.67, 1.7, -0.08]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder003.geometry}
      material={gltf.materials.Light}
      position={[0, 1.7, 1.03]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder004.geometry}
      material={gltf.materials.Light}
      position={[0.63, 1.7, 1.03]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder005.geometry}
      material={gltf.materials.Light}
      position={[-0.67, 1.7, 1.03]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube009.geometry}
      material={gltf.materials['Material.012']}
      position={[-0.51, -0.02, 1.33]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube019.geometry}
      material={gltf.materials.Material}
      position={[-0.87, 0.06, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube004.geometry}
      material={gltf.materials.Material}
      position={[-0.87, 1.67, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube007.geometry}
      material={gltf.materials['Material.006']}
      position={[-0.51, -0.02, 1.33]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube010.geometry}
      material={gltf.materials.Material}
      position={[-0.27, 0.06, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube013.geometry}
      material={gltf.materials['Material.006']}
      position={[-0.51, -0.02, 1.29]}
      scale={[1, 1, 0.98]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube014.geometry}
      material={gltf.materials.Material}
      position={[-0.27, 1.67, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube015.geometry}
      material={gltf.materials['Material.006']}
      position={[-0.51, -0.02, 1.33]}
      scale={[1, 0.99, 1]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube016.geometry}
      material={gltf.materials['Material.006']}
      position={[-0.51, -0.02, 1.33]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube017.geometry}
      material={gltf.materials.Material}
      position={[0.33, 0.06, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube020.geometry}
      material={gltf.materials.Material}
      position={[-0.22, 0.71, 0.62]}
      scale={[0.06, 0.02, 0.01]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube021.geometry}
      material={gltf.materials.Material}
      position={[-0.26, 0.71, 0.62]}
      scale={[1.48, 1.56, 1]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube024.geometry}
      material={gltf.materials['Material.006']}
      position={[-0.51, -0.02, 1.29]}
      scale={[1, 1, 0.98]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube025.geometry}
      material={gltf.materials.Material}
      position={[0.33, 1.67, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube027.geometry}
      material={gltf.materials['Material.006']}
      position={[-0.51, -0.02, 1.33]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube028.geometry}
      material={gltf.materials.Material}
      position={[0.92, 0.06, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube032.geometry}
      material={gltf.materials.Material}
      position={[0.92, 1.67, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane.geometry}
      material={gltf.materials.Floor}
      position={[-0.1, -0.02, -0.18]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane001.geometry}
      material={gltf.materials['Wall tiles']}
      position={[0.01, 0.07, -0.53]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane002.geometry}
      material={gltf.materials.Wall}
      position={[0.01, 0.48, -0.53]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane003.geometry}
      material={gltf.materials['Wall tiles']}
      position={[0.01, 0.91, -0.53]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane004.geometry}
      material={gltf.materials.Wall}
      position={[0.01, 1.33, -0.53]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane005.geometry}
      material={gltf.materials['Wall.001']}
      position={[0.01, 1.7, -0.53]}
      rotation={[Math.PI, 0, Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane006.geometry}
      material={gltf.materials['Wall.001']}
      position={[0.01, 1.72, 0.47]}
      rotation={[-Math.PI, 0, 0]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
