<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/guutz/Desktop/shenanigans/yava/my-project/static/models/ssj.glb --root /models/ --shadows --printwidth 120 --precision 2 --suspense
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'
  import { interactivity } from '@threlte/extras'
  interactivity()
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();
  import { AutoColliders } from '@threlte/rapier'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('/models/ssj.glb'))

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0.21, 0.57, 0.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.6}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_4.geometry}
        material={gltf.materials['Metal-Aluminium']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_4_1.geometry}
        material={gltf.materials['Surface-Whitewas']}
      />
    </T.Group>
    <AutoColliders shape={'trimesh'}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.D_Low.geometry}
        material={gltf.materials['Material.002']}
        position={[0.01, -0.06, -0.12]}
        rotation={[Math.PI / 2, 0, 0]}
        on:click={(e) => {
            dispatch('poop');
            e.stopPropagation();
          }
        }
      />
    </AutoColliders>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.D_Low001.geometry}
      material={gltf.materials['Material.002']}
      position={[0.59, -0.06, -0.12]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.D_Low003.geometry}
      material={gltf.materials['Material.002']}
      position={[-0.61, -0.06, -0.12]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder.geometry}
      material={gltf.materials.Light}
      position={[0, 1.7, -0.08]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder001.geometry}
      material={gltf.materials.Light}
      position={[0.63, 1.7, -0.08]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder002.geometry}
      material={gltf.materials.Light}
      position={[-0.67, 1.7, -0.08]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder003.geometry}
      material={gltf.materials.Light}
      position={[0, 1.7, 1.03]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder004.geometry}
      material={gltf.materials.Light}
      position={[0.63, 1.7, 1.03]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder005.geometry}
      material={gltf.materials.Light}
      position={[-0.67, 1.7, 1.03]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube009.geometry}
      material={gltf.materials['Material.012']}
      position={[-0.88, 1.05, 0.65]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube019.geometry}
      material={gltf.materials.Material}
      position={[-0.93, 0.08, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube004.geometry}
      material={gltf.materials.Material}
      position={[-0.93, 1.69, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube007.geometry}
      material={gltf.materials['Material.006']}
      position={[-0.28, 1.05, 0.65]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube010.geometry}
      material={gltf.materials.Material}
      position={[-0.32, 0.08, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube013.geometry}
      material={gltf.materials['Material.006']}
      position={[-0.31, 0.86, 0.13]}
      scale={[1, 1, 0.98]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube014.geometry}
      material={gltf.materials.Material}
      position={[-0.32, 1.69, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube015.geometry}
      material={gltf.materials['Material.006']}
      position={[0.06, 0.91, 0.65]}
      scale={[1, 0.99, 1]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube016.geometry}
      material={gltf.materials['Material.006']}
      position={[0.31, 1.05, 0.65]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube017.geometry}
      material={gltf.materials.Material}
      position={[0.27, 0.08, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube020.geometry}
      material={gltf.materials.Material}
      position={[-0.22, 0.71, 0.62]}
      scale={[0.06, 0.02, 0.01]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube021.geometry}
      material={gltf.materials.Material}
      position={[-0.25, 0.71, 0.62]}
      scale={[1.48, 1.56, 1]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube024.geometry}
      material={gltf.materials['Material.006']}
      position={[0.29, 0.86, 0.13]}
      scale={[1, 1, 0.98]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube025.geometry}
      material={gltf.materials.Material}
      position={[0.27, 1.69, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube027.geometry}
      material={gltf.materials['Material.006']}
      position={[0.9, 1.05, 0.65]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube028.geometry}
      material={gltf.materials.Material}
      position={[0.86, 0.08, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube032.geometry}
      material={gltf.materials.Material}
      position={[0.86, 1.69, 0.65]}
      scale={[0.62, 0.07, 1.2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane.geometry}
      material={gltf.materials.Floor}
      position={[-0.1, -0.02, -0.18]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane001.geometry}
      material={gltf.materials['Wall tiles']}
      position={[0.01, 0.07, -0.53]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane002.geometry}
      material={gltf.materials.Wall}
      position={[0.01, 0.48, -0.53]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane003.geometry}
      material={gltf.materials['Wall tiles']}
      position={[0.01, 0.91, -0.53]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane004.geometry}
      material={gltf.materials.Wall}
      position={[0.01, 1.33, -0.53]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane005.geometry}
      material={gltf.materials['Wall.001']}
      position={[0.01, 1.7, -0.53]}
      rotation={[Math.PI, 0, Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane006.geometry}
      material={gltf.materials['Wall.001']}
      position={[0.01, 1.72, 0.47]}
      rotation={[-Math.PI, 0, 0]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
