<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/guutz/Desktop/shenanigans/yava/my-project/static/models/threlte.glb --root /models/ --shadows --printwidth 120 --precision 2 --suspense
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('/models/threlte.glb'))

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials.Material}
      position={[0, 1, 2]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
